version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092
    depends_on:
      - zookeeper


  db:
    image: postgres:15
    container_name: chat-db
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "5466:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  api:
    build: ./api
    container_name: chat-api
    depends_on:
      - kafka
      - db
      - minio
    environment:
      PORT: "3000"
      DATABASE_URL: "postgres://chat:chatpass@db:5432/chatdb"
      KAFKA_BROKER: "kafka:9092"
      JWT_SECRET: "supersecretjwt"

      S3_ENDPOINT: "http://minio:9000"        
      S3_PUBLIC_ENDPOINT: "http://localhost:9000"  
      S3_ACCESS_KEY: "minio"
      S3_SECRET_KEY: "minio123"
      S3_BUCKET: "uploads"
    ports:
      - "3003:3000"

  worker:
    build: ./worker
   # container_name: chat-worker
    depends_on:
      - kafka
      - db
    environment:
      DATABASE_URL: "postgres://chat:chatpass@db:5432/chatdb"
      KAFKA_BROKER: "kafka:9092"
      CALLBACK_URL: "http://chat-api:3000/api/v1/events" #eu nao sei se precisa disso mesmo
      METRICS_PORT: "3002"
    ports:
    - "3002"  

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

  connector_whatsapp_mock:
    build: ./connector_whatsapp_mock
   # container_name: connector_whatsapp_mock
    depends_on:
      - kafka
      - api
    environment:
      - KAFKA_BROKER=kafka:9092
      - CALLBACK_URL=http://api:3000/v1/events/message-delivered
    ports:
      - "4001:4001"  

  connector_instagram_mock:
    build: ./connector_instagram_mock
   # container_name: connector_instagram_mock
    depends_on:
      - kafka
      - api
    environment:
      - KAFKA_BROKER=kafka:9092
      - CALLBACK_URL=http://api:3000/v1/events/message-delivered
    ports:
      - "4002:4000"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3004:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin #a senha nova é admin123 e o user é admin
    depends_on:
      - prometheus

